import { prisma } from "../src/lib/db";
import { analyzeEventWithHaiku } from "../src/lib/premium/haiku-events-curator";

import { EventData } from '../types/event';

export const seasonalEvents: EventData[] = [
  // SPRING EVENTS
  {
    title: 'Cherry Blossom Festivals - Central Park',
    description: 'Celebrate spring as thousands of cherry blossom trees bloom throughout Central Park. Visit Cherry Hill and other scenic locations to experience the beauty of pink and white petals.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-03-28'),
    venue: 'Central Park - Cherry Hill',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Sakura Matsuri - Brooklyn Botanic Garden',
    description: 'Experience Japanese culture and tradition during Brooklyn\'s premier cherry blossom festival. Features live music, traditional performances, food vendors, and hundreds of blooming cherry trees.',
    category: 'culture' as const,
    startsAt: new Date('2026-04-18'),
    venue: 'Brooklyn Botanic Garden',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'Hanami Nights - Brooklyn Botanic Garden',
    description: 'Evening celebration of cherry blossoms with live music and special performances. Experience the magic of illuminated trees at twilight with cultural entertainment.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-04-22'),
    venue: 'Brooklyn Botanic Garden',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'Easter Bonnet Festival - Fifth Avenue',
    description: 'Transform Fifth Avenue into a colorful catwalk of extravagant hats, creative costumes, and lively energy. A New York City tradition celebrating spring and Easter with style.',
    category: 'local' as const,
    startsAt: new Date('2026-04-05'),
    venue: 'Fifth Avenue (49th to 57th Street)',
    neighborhood: 'Manhattan',
  },
  {
    title: 'St. Patrick\'s Day Parade',
    description: 'The world\'s oldest and largest St. Patrick\'s Day Parade with 150,000 marchers celebrating Irish heritage. Features marching bands, dance groups, and community organizations.',
    category: 'culture' as const,
    startsAt: new Date('2026-03-17'),
    venue: 'Fifth Avenue (44th to 79th Street)',
    neighborhood: 'Manhattan',
  },

  // SUMMER EVENTS
  {
    title: 'Shakespeare in the Park - Romeo and Juliet',
    description: 'Free outdoor Shakespeare featuring a new production of Romeo and Juliet directed by Saheem Ali at the newly renovated Delacorte Theater in Central Park.',
    category: 'culture' as const,
    startsAt: new Date('2026-06-01'),
    venue: 'Delacorte Theater - Central Park',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Shakespeare in the Park - The Winter\'s Tale',
    description: 'Classic Shakespeare comedy directed by Daniel Sullivan. Free tickets available at the Delacorte Theater in Central Park daily.',
    category: 'culture' as const,
    startsAt: new Date('2026-07-15'),
    venue: 'Delacorte Theater - Central Park',
    neighborhood: 'Manhattan',
  },
  {
    title: 'SummerStage - Central Park Concert Series',
    description: 'Capital One City Parks Foundation presents 80+ free outdoor performances featuring diverse artists across jazz, hip-hop, Latin, indie and contemporary genres throughout the summer.',
    category: 'culture' as const,
    startsAt: new Date('2026-06-01'),
    venue: 'Central Park - SummerStage',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Movies with a View - Brooklyn Bridge Park',
    description: 'Free outdoor cinema on Thursday evenings at Brooklyn Bridge Park\'s Pier 1 Harbor View Lawn. Movies begin at sundown during July and August.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-07-02'),
    venue: 'Brooklyn Bridge Park - Pier 1',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'Bryant Park Summer Movies on the Lawn',
    description: 'Free outdoor screenings every Monday night. The lawn opens at 5 PM with movies starting around 8 PM. Part of Bryant Park\'s 31-year tradition of summer cinema.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-06-07'),
    venue: 'Bryant Park',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Paramount+ Movie Nights in Brooklyn',
    description: 'Free weekly outdoor screenings throughout Brooklyn in multiple parks including McCarren Park, Fort Greene Park, Prospect Park, and Coney Island Beach.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-07-01'),
    venue: 'Multiple Brooklyn Parks',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'NYC Beach Season Opening',
    description: 'Official opening of NYC public beaches including Coney Island, Orchard Beach, and Rockaway Beach. Lifeguards on duty and concessions available.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-05-23'),
    venue: 'Citywide Beaches',
    neighborhood: 'Citywide',
  },
  {
    title: 'NYC Pool Season Opening',
    description: 'Opening of all NYC Parks public swimming pools across the five boroughs with lap swimming, recreational swimming, and water classes.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-06-15'),
    venue: 'NYC Public Pools',
    neighborhood: 'Citywide',
  },
  {
    title: 'Shakespeare for the City Mobile Unit - As You Like It',
    description: 'Free touring production of As You Like It bringing Shakespeare to neighborhoods throughout all five boroughs during May and summer months.',
    category: 'culture' as const,
    startsAt: new Date('2026-05-01'),
    venue: 'Various Parks - Five Boroughs',
    neighborhood: 'Citywide',
  },

  // FALL EVENTS
  {
    title: 'Fall Foliage Guided Hikes - Central Park',
    description: 'Urban Park Rangers lead free guided hikes through Central Park\'s North Woods to experience colorful autumn foliage. Educational and scenic exploration of fall colors.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-10-01'),
    venue: 'Central Park - North Woods',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Fall Forest Weekend - NYBG',
    description: 'New York Botanical Garden\'s celebration of autumn with guided tours, activities, and educational demonstrations through old-growth woodlands showcasing vibrant fall colors.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-11-01'),
    venue: 'New York Botanical Garden',
    neighborhood: 'Bronx',
  },
  {
    title: 'Halloween Pumpkin Flotilla - Central Park',
    description: 'Float decorated carved pumpkins across Harlem Meer at twilight. Features pumpkin carving demonstrations, costume parade, live music, and free entertainment for all ages.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-10-24'),
    venue: 'Central Park - Harlem Meer',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Urban Pumpkin Patch - Atlantic Terminal Mall',
    description: 'Brooklyn\'s urban pumpkin patch with 1,000 pumpkins to decorate. Features haunted truck, costume dance party, face painting, art van, and family activities.',
    category: 'local' as const,
    startsAt: new Date('2026-10-10'),
    venue: 'Atlantic Terminal Mall',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'Queens County Farm Museum Pumpkin Patch',
    description: 'Pick your own pumpkins and explore a 47-acre working farm. October celebration of harvest season with farm activities and seasonal festivities.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-10-01'),
    venue: 'Queens County Farm Museum',
    neighborhood: 'Queens',
  },

  // WINTER & HOLIDAY EVENTS
  {
    title: 'Bank of America Winter Village at Bryant Park',
    description: 'NYC\'s premier holiday market and ice skating destination. Over 180 vendor kiosks offering artisan goods, local crafts, holiday gifts, and food. 17,000 sq ft free ice skating rink.',
    category: 'seasonal' as const,
    startsAt: new Date('2025-10-24'),
    venue: 'Bryant Park',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Rockefeller Center Christmas Tree Lighting',
    description: 'Iconic lighting ceremony of the 75-foot Norway spruce decorated with 50,000 LED lights and a 900-pound Swarovski star. Live entertainment and holiday celebration.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-12-02'),
    venue: 'Rockefeller Center',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Rockefeller Center Ice Skating Rink',
    description: 'World-famous ice skating at the heart of Rockefeller Center. Open daily 9 AM to midnight throughout the winter season with views of the decorated plaza.',
    category: 'seasonal' as const,
    startsAt: new Date('2025-10-11'),
    venue: 'Rockefeller Center',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Grand Army Plaza Hanukkah Menorah - Manhattan',
    description: 'Lighting of the world\'s largest Hanukkah menorah in Manhattan\'s Grand Army Plaza at 59th Street. Eight nights of celebration with music and community gathering.',
    category: 'culture' as const,
    startsAt: new Date('2026-12-16'),
    venue: 'Grand Army Plaza (59th Street)',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Prospect Park Hanukkah Menorah - Brooklyn',
    description: 'Brooklyn\'s largest menorah lighting with official Hanukkah kickoff concert, free latkes, and gifts for children every night of the holiday.',
    category: 'culture' as const,
    startsAt: new Date('2026-12-16'),
    venue: 'Grand Army Plaza - Prospect Park',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'NYC Kwanzaa Festival Celebration',
    description: 'City\'s 18th annual weeklong Kwanzaa festival honoring African heritage and seven principles. Features daily candle lightings, youth performances, dance, drumming, and art workshops.',
    category: 'culture' as const,
    startsAt: new Date('2026-12-26'),
    venue: 'Various NYC Parks',
    neighborhood: 'Citywide',
  },
  {
    title: 'Valentine\'s Day at Rockefeller Center',
    description: 'Romantic dining experiences at Le Rock and NARO with prix-fixe menus, plus special Valentine\'s celebrations throughout Rockefeller Center plaza.',
    category: 'local' as const,
    startsAt: new Date('2026-02-14'),
    venue: 'Rockefeller Center',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Orchid Show - New York Botanical Garden',
    description: 'Spectacular exhibition of rare and exotic orchids. Perfect Valentine\'s Day weekend destination featuring thousands of flowering orchids in stunning displays.',
    category: 'culture' as const,
    startsAt: new Date('2026-02-07'),
    venue: 'New York Botanical Garden',
    neighborhood: 'Bronx',
  },
  {
    title: 'Times Square New Year\'s Eve Ball Drop',
    description: 'Iconic midnight countdown in Times Square with famous ball drop, confetti, fireworks, and entertainment. America250 celebration with special red, white, and blue themed festivities.',
    category: 'local' as const,
    startsAt: new Date('2026-12-31'),
    venue: 'Times Square',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Central Park New Year\'s Eve Fireworks',
    description: 'Celebratory fireworks display launched from area between Bow Bridge and Cherry Hill (71st-74th Streets) welcoming the New Year with spectacular light show.',
    category: 'seasonal' as const,
    startsAt: new Date('2026-12-31'),
    venue: 'Central Park',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Macy\'s Thanksgiving Day Parade - 100th Anniversary',
    description: 'America\'s most iconic Thanksgiving parade with enormous character balloons, marching bands, floats, and live performances. Parade travels down Manhattan\'s streets since 1924.',
    category: 'local' as const,
    startsAt: new Date('2026-11-26'),
    venue: 'Manhattan Streets (77th Street to Broadway)',
    neighborhood: 'Manhattan',
  },
  {
    title: 'Memorial Day Parade - Brooklyn',
    description: 'Brooklyn\'s 156th annual Memorial Day Parade honoring fallen service members. Community parade with military units, civic organizations, and neighborhood participants.',
    category: 'local' as const,
    startsAt: new Date('2026-05-25'),
    venue: 'Brooklyn',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'DanceAfrica Festival - BAM',
    description: 'Memorial Day weekend celebration of African and diaspora dance, music, and culture. Features multi-day performances, outdoor bazaar, workshops, films, and parties.',
    category: 'culture' as const,
    startsAt: new Date('2026-05-22'),
    venue: 'Brooklyn Academy of Music',
    neighborhood: 'Brooklyn',
  },
  {
    title: 'Labor Day Weekend - Richmond County Fair',
    description: 'Staten Island\'s celebration featuring circus performers, petting zoo, cartoon characters, live music, rides, food, and pie-eating contests over Labor Day weekend.',
    category: 'local' as const,
    startsAt: new Date('2026-09-05'),
    venue: 'Richmondtown, Staten Island',
    neighborhood: 'Staten Island',
  },
];
